import sys
import os
import json
import time
from groq import Groq
from dotenv import load_dotenv
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from rag.retriever import get_answer

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Test questions we'll evaluate our RAG against
TEST_QUESTIONS = [
    {
        "question": "What export control risks does NVIDIA face?",
        "company_filter": "nvidia"
    },
    {
        "question": "What were Apple's main revenue sources?",
        "company_filter": "apple"
    },
    {
        "question": "What are Microsoft's key AI investments?",
        "company_filter": "microsoft"
    },
    {
        "question": "What risks does Tesla mention regarding autonomous driving?",
        "company_filter": "tesla"
    },
    {
        "question": "How does Amazon describe its AWS business?",
        "company_filter": "amazon"
    },
    {
        "question": "Which companies mention AI as a growth opportunity?",
        "company_filter": None
    },
    {
        "question": "What do these companies say about competition?",
        "company_filter": None
    },
]


def build_judge_prompt(question: str, answer: str, chunks: list) -> str:
    """
    Build the prompt for the judge LLM.
    """
    context = "\n\n---\n\n".join([
        chunk["text_preview"] for chunk in chunks
    ])

    prompt = f"""You are an expert evaluator of RAG (Retrieval Augmented Generation) systems.

You will be given:
- A question
- An answer generated by a RAG system
- The source chunks that were retrieved to generate the answer

Your job is to score the answer on 3 metrics from 1 to 5.

Scoring criteria:

FAITHFULNESS (1-5):
- 5: Every claim in the answer is fully supported by the source chunks
- 3: Most claims are supported but some are vague or slightly unsupported
- 1: Answer contains claims not found in or contradicted by the chunks

ANSWER RELEVANCE (1-5):
- 5: Answer directly and completely addresses the question
- 3: Answer partially addresses the question
- 1: Answer is off-topic or does not address the question

CONTEXT PRECISION (1-5):
- 5: All retrieved chunks are highly relevant to the question
- 3: Some chunks are relevant, some are noise
- 1: Most chunks are irrelevant to the question

---

Question: {question}

Answer: {answer}

Source chunks retrieved:
{context}

---

Respond ONLY with a JSON object in this exact format, nothing else:
{{
  "faithfulness": <score 1-5>,
  "answer_relevance": <score 1-5>,
  "context_precision": <score 1-5>,
  "reasoning": "<one sentence explaining your scores>"
}}"""

    return prompt


def evaluate_single(question: str, answer: str, sources: list) -> dict:
    """
    Send one answer to the judge LLM and get scores back.
    """
    client = Groq(api_key=GROQ_API_KEY)

    judge_prompt = build_judge_prompt(question, answer, sources)

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "user", "content": judge_prompt}
        ],
        temperature=0.0  # zero temperature for consistent scoring
    )

    raw = response.choices[0].message.content.strip()

    # Parse the JSON response
    try:
        scores = json.loads(raw)
    except json.JSONDecodeError:
        # Sometimes LLM adds extra text — try to extract JSON
        start = raw.find("{")
        end = raw.rfind("}") + 1
        scores = json.loads(raw[start:end])

    return scores


def run_evaluation() -> list:
    """
    Run evaluation across all test questions.
    """
    print("=== Starting Evaluation ===\n")
    print(f"Total questions: {len(TEST_QUESTIONS)}\n")

    results = []

    for i, item in enumerate(TEST_QUESTIONS):
        question = item["question"]
        company_filter = item["company_filter"]

        print(f"[{i+1}/{len(TEST_QUESTIONS)}] {question}")

        # Step 1: Get RAG answer
        rag_result = get_answer(question, company_filter)

        # Step 2: Judge the answer
        scores = evaluate_single(
            question=rag_result["question"],
            answer=rag_result["answer"],
            sources=rag_result["sources"]
        )

        # Step 3: Store result
        result = {
            "question": question,
            "company_filter": company_filter,
            "answer": rag_result["answer"],
            "sources": rag_result["sources"],
            "faithfulness": scores.get("faithfulness", 0),
            "answer_relevance": scores.get("answer_relevance", 0),
            "context_precision": scores.get("context_precision", 0),
            "reasoning": scores.get("reasoning", ""),
            "overall": round(
                (scores.get("faithfulness", 0) +
                 scores.get("answer_relevance", 0) +
                 scores.get("context_precision", 0)) / 3, 2
            )
        }

        results.append(result)

        print(f"  Faithfulness:      {result['faithfulness']}/5")
        print(f"  Answer Relevance:  {result['answer_relevance']}/5")
        print(f"  Context Precision: {result['context_precision']}/5")
        print(f"  Overall:           {result['overall']}/5")
        print(f"  Reasoning: {result['reasoning']}")
        print()

        # Wait between calls to avoid rate limiting
        time.sleep(1)

    # Print summary
    avg_faithfulness = round(sum(r["faithfulness"] for r in results) / len(results), 2)
    avg_relevance = round(sum(r["answer_relevance"] for r in results) / len(results), 2)
    avg_precision = round(sum(r["context_precision"] for r in results) / len(results), 2)
    avg_overall = round(sum(r["overall"] for r in results) / len(results), 2)

    print("=== Summary ===")
    print(f"Avg Faithfulness:      {avg_faithfulness}/5")
    print(f"Avg Answer Relevance:  {avg_relevance}/5")
    print(f"Avg Context Precision: {avg_precision}/5")
    print(f"Avg Overall:           {avg_overall}/5")

    return results


if __name__ == "__main__":
    run_evaluation()